# Generated by Django 6.0.1 on 2026-02-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaprod',
            old_name='updates',
            new_name='updated',
        ),
    ]
